name: Deploy Docker Image from Docker Hub

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2_key.pem
          chmod 600 ~/.ssh/ec2_key.pem

      - name: Pull and Run Docker Image on EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          debug: true
          script: |
            # Stop any existing container with the same name
            docker stop my-container || true
            docker rm my-container || true

            # Pull the Docker image from Docker Hub
            docker pull ${{ secrets.DOCKER_USERNAME }}/cs203app:latest

            # Run the Docker image
            docker run -d --name my-container -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/your-image-name:latest
