name: Deploy Docker Image from Docker Hub to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Set up SSH key for EC2 access
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2_key.pem
          chmod 600 ~/.ssh/ec2_key.pem

      # Pull and run the Docker image on the EC2 instance
      - name: Pull and Run Docker Image on EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22  # Specify SSH port, default is 22
          debug: true
          script: |  
            
            sudo service docker start
            
            # Logging into Docker Hub 
            echo ${{ secrets.DOCKER_PASSWORD }} | sudo docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
            
            # Pull the latest Docker image from Docker Hub
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/aws-demo:v9.1

            # Run the Docker container
            sudo docker run -d \
              --name CS-203APP \
              -p 8080:8080 \
              ${{ secrets.DOCKER_USERNAME }}/aws-demo:v9.1

            # Optional: Verify the container is running
            docker ps -a | grep CS-203APP

      # Clean up local SSH key (optional security measure)
      - name: Clean up SSH key
        if: always()
        run: rm -f ~/.ssh/ec2_key.pem
