name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and test
        uses: docker/build-push-action@v6
        with:
          target: test
          load: true
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./cs203system  # Path where the Dockerfile is located
          file: ./cs203system/Dockerfile  # Path to the Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/$(github.event.repository.name):latest
          load: true
